<?php
/**
 * Plugin Name: WooCommerce Custom Redirect Manager
 * Description: Dynamically evaluates completed orders and redirects users based on configurable backend rules.
 * Version:     1.0.1
 * Author:      Digitally Disruptive - Donald Raymundo
 * Author URI:  https://digitallydisruptive.co.uk/
 * Text Domain: dd-wc-redirect
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

/**
 * Class DD_WC_Redirect_Manager
 * Handles the registration of the admin interface, saving of repeater rules,
 * and the frontend logic for order-received redirections.
 */
class DD_WC_Redirect_Manager {

    /**
     * Initializes the plugin hooks.
     * @return void
     */
    public function __construct() {
        add_action( 'admin_menu', array( $this, 'register_admin_menu' ) );
        add_action( 'admin_init', array( $this, 'save_settings' ) );
        add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_assets' ) );
        add_action( 'template_redirect', array( $this, 'dd_custom_thank_you_redirect_based_on_product' ) );
    }

    /**
     * Registers the custom submenu page under the main WooCommerce menu.
     * @return void
     */
    public function register_admin_menu() {
        add_submenu_page(
            'woocommerce',
            'Redirect Rules',
            'Redirect Rules',
            'manage_woocommerce',
            'dd-wc-redirects',
            array( $this, 'render_admin_page' )
        );
    }

    /**
     * Enqueues necessary scripts and styles for the backend UI, specifically
     * WooCommerce's selectWoo for dynamic product searching.
     * @param string $hook The current admin page hook.
     * @return void
     */
    public function enqueue_admin_assets( $hook ) {
        if ( 'woocommerce_page_dd-wc-redirects' !== $hook ) {
            return;
        }
        
        wp_enqueue_script( 'wc-enhanced-select' );
        wp_enqueue_style( 'woocommerce_admin_styles', WC()->plugin_url() . '/assets/css/admin.css' );
    }

    /**
     * Intercepts POST requests on the admin page to sanitize and serialize 
     * the repeater field data into the options table.
     * @return void
     */
    public function save_settings() {
        if ( ! isset( $_POST['dd_redirect_nonce'] ) || ! wp_verify_nonce( $_POST['dd_redirect_nonce'], 'dd_save_redirects' ) ) {
            return;
        }

        if ( ! current_user_can( 'manage_woocommerce' ) ) {
            return;
        }

        $rules = isset( $_POST['dd_rules'] ) ? (array) $_POST['dd_rules'] : array();
        $sanitized_rules = array();

        foreach ( $rules as $rule ) {
            // Skip empty rows generated by the JS template
            if ( empty( $rule['products'] ) && empty( $rule['page_id'] ) && empty( $rule['external_url'] ) ) {
                continue;
            }

            $sanitized_rules[] = array(
                'products'      => isset( $rule['products'] ) ? array_map( 'absint', (array) $rule['products'] ) : array(),
                'redirect_type' => isset( $rule['redirect_type'] ) ? sanitize_text_field( $rule['redirect_type'] ) : 'page',
                'page_id'       => isset( $rule['page_id'] ) ? absint( $rule['page_id'] ) : 0,
                'external_url'  => isset( $rule['external_url'] ) ? esc_url_raw( $rule['external_url'] ) : '',
            );
        }

        update_option( 'dd_wc_redirect_rules', $sanitized_rules );
        
        add_settings_error( 'dd_redirect_messages', 'dd_redirect_updated', 'Rules updated successfully.', 'updated' );
    }

    /**
     * Renders the HTML for the backend admin page, including the tabbed interface 
     * and the interactive repeater fields.
     * @return void
     */
    public function render_admin_page() {
        $rules = get_option( 'dd_wc_redirect_rules', array() );
        
        // Ensure at least one empty rule exists for the UI
        if ( empty( $rules ) ) {
            $rules[] = array( 'products' => array(), 'redirect_type' => 'page', 'page_id' => 0, 'external_url' => '' );
        }
        ?>
        <div class="wrap">
            <h1>WooCommerce Custom Redirects</h1>
            <?php settings_errors( 'dd_redirect_messages' ); ?>

            <h2 class="nav-tab-wrapper" id="dd-tabs">
                <a href="#tab-rules" class="nav-tab nav-tab-active">Redirect Rules</a>
            </h2>

            <form method="POST" action="">
                <?php wp_nonce_field( 'dd_save_redirects', 'dd_redirect_nonce' ); ?>

                <div id="tab-rules" class="dd-tab-content active">
                    <p>Configure which products trigger a redirect and where the customer should be sent.</p>
                    
                    <div id="dd-repeater-container">
                        <?php foreach ( $rules as $index => $rule ) : ?>
                            <?php $this->render_rule_template( $index, $rule ); ?>
                        <?php endforeach; ?>
                    </div>
                    
                    <button type="button" class="button button-primary" id="dd-add-rule">Add New Rule</button>
                </div>

                <p class="submit">
                    <button type="submit" class="button button-primary">Save Changes</button>
                </p>
            </form>
        </div>

        <?php $this->render_inline_styles_and_scripts(); ?>
        <?php
    }

    /**
     * Outputs the HTML structure for a single repeater row.
     * @param int|string $index The array index for field naming.
     * @param array $rule The saved values for this rule instance.
     * @return void
     */
    private function render_rule_template( $index, $rule ) {
        $products      = isset( $rule['products'] ) ? $rule['products'] : array();
        $redirect_type = isset( $rule['redirect_type'] ) ? $rule['redirect_type'] : 'page';
        $page_id       = isset( $rule['page_id'] ) ? $rule['page_id'] : 0;
        $external_url  = isset( $rule['external_url'] ) ? $rule['external_url'] : '';
        ?>
        <div class="dd-rule-item postbox" data-index="<?php echo esc_attr( $index ); ?>">
            <div class="dd-rule-header">
                <h3 class="hndle">Rule <span class="rule-index-label"><?php echo esc_html( (int)$index + 1 ); ?></span></h3>
                <div class="dd-rule-actions">
                    <button type="button" class="button button-small dd-collapse">Collapse</button>
                    <button type="button" class="button button-small dd-duplicate">Duplicate</button>
                    <button type="button" class="button button-small dd-move-up">Up</button>
                    <button type="button" class="button button-small dd-move-down">Down</button>
                    <button type="button" class="button button-small dd-delete" style="color:red; border-color:red;">Delete</button>
                </div>
            </div>
            <div class="dd-rule-body inside">
                <table class="form-table">
                    <tr>
                        <th scope="row"><label>Trigger Products</label></th>
                        <td>
                            <select name="dd_rules[<?php echo esc_attr( $index ); ?>][products][]" class="wc-product-search" multiple="multiple" style="width: 100%;" data-placeholder="Search for products..." data-action="woocommerce_json_search_products_and_variations">
                                <?php
                                foreach ( $products as $product_id ) {
                                    $product = wc_get_product( $product_id );
                                    if ( is_object( $product ) ) {
                                        echo '<option value="' . esc_attr( $product_id ) . '" selected="selected">' . wp_kses_post( $product->get_formatted_name() ) . '</option>';
                                    }
                                }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><label>Redirect Destination</label></th>
                        <td>
                            <select name="dd_rules[<?php echo esc_attr( $index ); ?>][redirect_type]" class="dd-redirect-type" style="margin-bottom: 10px;">
                                <option value="page" <?php selected( $redirect_type, 'page' ); ?>>Internal Page</option>
                                <option value="external" <?php selected( $redirect_type, 'external' ); ?>>External Link</option>
                            </select>

                            <div class="dd-type-wrap dd-type-page" style="<?php echo $redirect_type === 'page' ? '' : 'display:none;'; ?>">
                                <?php
                                wp_dropdown_pages( array(
                                    'name'             => 'dd_rules[' . esc_attr( $index ) . '][page_id]',
                                    'show_option_none' => '-- Select a Page --',
                                    'selected'         => $page_id,
                                ) );
                                ?>
                            </div>

                            <div class="dd-type-wrap dd-type-external" style="<?php echo $redirect_type === 'external' ? '' : 'display:none;'; ?>">
                                <input type="url" name="dd_rules[<?php echo esc_attr( $index ); ?>][external_url]" value="<?php echo esc_attr( $external_url ); ?>" placeholder="https://example.com" class="regular-text">
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <?php
    }

    /**
     * Outputs the CSS and JavaScript required for the UI logic (Tabs and Repeater behavior).
     * @return void
     */
    private function render_inline_styles_and_scripts() {
        ?>
        <style>
            .dd-rule-header { display: flex; justify-content: space-between; align-items: center; padding: 10px; background: #f9f9f9; border-bottom: 1px solid #e5e5e5; cursor: move; }
            .dd-rule-header h3 { margin: 0; }
            .dd-rule-item.collapsed .dd-rule-body { display: none; }
            #dd-repeater-container { margin-top: 20px; margin-bottom: 20px; }
            .dd-rule-actions button { margin-left: 5px; }
        </style>

        <script>
        jQuery(document).ready(function($) {
            // Tab Interface Logic (Preserved for future tab implementations)
            $('#dd-tabs a').on('click', function(e) {
                e.preventDefault();
                $('#dd-tabs a').removeClass('nav-tab-active');
                $(this).addClass('nav-tab-active');
                
                $('.dd-tab-content').hide();
                $($(this).attr('href')).show();
            });

            // Toggle Field Visibility based on Redirect Type
            $(document).on('change', '.dd-redirect-type', function() {
                var $wrap = $(this).closest('td');
                $wrap.find('.dd-type-wrap').hide();
                $wrap.find('.dd-type-' + $(this).val()).show();
            });

            // Initialize selectWoo (WooCommerce Select2 Wrapper)
            function initSelectWoo($context) {
                $context.find('.wc-product-search').each(function() {
                    $(this).selectWoo({
                        ajax: {
                            url: ajaxurl,
                            dataType: 'json',
                            delay: 250,
                            data: function(params) {
                                return {
                                    term: params.term,
                                    action: 'woocommerce_json_search_products_and_variations',
                                    security: wc_enhanced_select_params.search_products_nonce
                                };
                            },
                            processResults: function(data) {
                                var terms = [];
                                if (data) {
                                    $.each(data, function(id, text) {
                                        terms.push({ id: id, text: text });
                                    });
                                }
                                return { results: terms };
                            }
                        }
                    });
                });
            }
            
            initSelectWoo($('#dd-repeater-container'));

            // Repeater Functionality: Update Index Names
            function updateIndices() {
                $('#dd-repeater-container .dd-rule-item').each(function(index) {
                    $(this).find('.rule-index-label').text(index + 1);
                    $(this).attr('data-index', index);
                    
                    $(this).find('[name^="dd_rules["]').each(function() {
                        var name = $(this).attr('name');
                        if (name) {
                            var newName = name.replace(/dd_rules\[\d+\]/, 'dd_rules[' + index + ']');
                            $(this).attr('name', newName);
                        }
                    });
                });
            }

            // Add New Rule
            $('#dd-add-rule').on('click', function() {
                var $firstRow = $('.dd-rule-item').first();
                // Destroy selectWoo before cloning to prevent ID conflicts
                $firstRow.find('.wc-product-search').selectWoo('destroy');
                
                var $clone = $firstRow.clone();
                $clone.find('input, select').val('');
                $clone.find('.wc-product-search').empty(); // Clear selected options
                $clone.removeClass('collapsed');
                
                $('#dd-repeater-container').append($clone);
                
                // Re-init both original and clone
                initSelectWoo($firstRow);
                initSelectWoo($clone);
                updateIndices();
            });

            // Duplicate Rule
            $(document).on('click', '.dd-duplicate', function(e) {
                e.preventDefault();
                var $row = $(this).closest('.dd-rule-item');
                $row.find('.wc-product-search').selectWoo('destroy');
                
                var $clone = $row.clone();
                $row.after($clone);
                
                initSelectWoo($row);
                initSelectWoo($clone);
                updateIndices();
            });

            // Delete Rule
            $(document).on('click', '.dd-delete', function(e) {
                e.preventDefault();
                if ($('.dd-rule-item').length > 1) {
                    $(this).closest('.dd-rule-item').remove();
                    updateIndices();
                } else {
                    alert('You must have at least one rule.');
                }
            });

            // Move Up
            $(document).on('click', '.dd-move-up', function(e) {
                e.preventDefault();
                var $row = $(this).closest('.dd-rule-item');
                if ($row.prev('.dd-rule-item').length) {
                    $row.insertBefore($row.prev('.dd-rule-item'));
                    updateIndices();
                }
            });

            // Move Down
            $(document).on('click', '.dd-move-down', function(e) {
                e.preventDefault();
                var $row = $(this).closest('.dd-rule-item');
                if ($row.next('.dd-rule-item').length) {
                    $row.insertAfter($row.next('.dd-rule-item'));
                    updateIndices();
                }
            });

            // Collapse / Expand Rule
            $(document).on('click', '.dd-collapse', function(e) {
                e.preventDefault();
                var $row = $(this).closest('.dd-rule-item');
                $row.toggleClass('collapsed');
                $(this).text($row.hasClass('collapsed') ? 'Expand' : 'Collapse');
            });
        });
        </script>
        <?php
    }

    /**
     * Evaluates the completed order and redirects the user to a custom thank you page
     * if predefined target product IDs are found within the order items, based on dynamic rules.
     *
     * @return void
     */
    public function dd_custom_thank_you_redirect_based_on_product() {
        // 1. Verify execution context: Ensure this only runs on the WooCommerce 'order-received' endpoint.
        if ( ! function_exists( 'is_wc_endpoint_url' ) || ! is_wc_endpoint_url( 'order-received' ) || empty( $_GET['key'] ) ) {
            return;
        }

        global $wp;

        // 2. Extract the order ID from the global $wp query variables.
        $order_id = isset( $wp->query_vars['order-received'] ) ? intval( $wp->query_vars['order-received'] ) : 0;

        if ( ! $order_id ) {
            return;
        }

        // 3. Instantiate the WC_Order object.
        $order = wc_get_order( $order_id );

        if ( ! $order || ! is_a( $order, 'WC_Order' ) ) {
            return;
        }

        // 4. Retrieve dynamic rules configured in the backend UI.
        $rules = get_option( 'dd_wc_redirect_rules', array() );
        
        if ( empty( $rules ) ) {
            return; // No rules configured, exit early.
        }

        // 5. Gather all product and variation IDs from the current order.
        $order_product_ids = array();
        foreach ( $order->get_items() as $item ) {
            $order_product_ids[] = $item->get_product_id();
            if ( $item->get_variation_id() ) {
                $order_product_ids[] = $item->get_variation_id();
            }
        }

        // 6. Iterate through rules. Evaluation halts and executes redirect on the first match.
        foreach ( $rules as $rule ) {
            $target_products = isset( $rule['products'] ) ? (array) $rule['products'] : array();
            
            // Check if any purchased items intersect with the current rule's targets.
            $intersection = array_intersect( $order_product_ids, $target_products );

            // 7. Execute the redirect if the evaluation returns true.
            if ( ! empty( $intersection ) ) {
                $redirect_url = '';
                
                if ( $rule['redirect_type'] === 'page' && ! empty( $rule['page_id'] ) ) {
                    $redirect_url = get_permalink( $rule['page_id'] );
                } elseif ( $rule['redirect_type'] === 'external' && ! empty( $rule['external_url'] ) ) {
                    $redirect_url = esc_url_raw( $rule['external_url'] );
                }

                if ( $redirect_url ) {
                    wp_safe_redirect( $redirect_url );
                    exit;
                }
            }
        }
    }
}

// Instantiate the class to boot the plugin logic.
new DD_WC_Redirect_Manager();